name: Run main.py

on:
  schedule:
    - cron: '0 */14 * * *' # At 00:00 every 14 days

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to the GitHub runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Install the Python version needed
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute Python script
        env:
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }} # Pass the secret to the script
        run: python main.py
